//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bookTicket()
        {
            this.cancelTickets = new HashSet<cancelTicket>();
        }
    
        public decimal Book_Id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> train_no { get; set; }
        public Nullable<double> total_fare { get; set; }
        public Nullable<System.DateTime> Booking_Date_Time { get; set; }
        public string Class_type { get; set; }
        public int NumberTickets { get; set; }
        public string Status { get; set; }
    
        public virtual train train { get; set; }
        public virtual user_details user_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cancelTicket> cancelTickets { get; set; }
    }
}
